[package]
name = "sudoku"
version = "0.1.0"
authors = ["Marcus Xu <xumarcus.sg@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"